// @flow
export const itemDividerColor = '#DEDEE1'
export const textColor = '#333'
export const tagTextColor = '#555'
export const tagBackgroundColor = '#fffcd7'
export const tagBorderColor = '#d5d458'
export const metaColor = '#888'
export const itemHighlightColor = '#EAF4FF'
export const accentColor = '#E53935'
export const accentDarkColor = '#b71c1c'
export const secondaryColor = '#1565C0'
