// flow-typed signature: ee50e953305ce7e620d457fbe81aa293
// flow-typed version: <<STUB>>/eslint-config_v^0.3.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config/dist/base-rules' {
  declare module.exports: any
}

declare module 'eslint-config/dist/generate-eslintrc' {
  declare module.exports: any
}

declare module 'eslint-config/dist/index' {
  declare module.exports: any
}

declare module 'eslint-config/dist/logger' {
  declare module.exports: any
}

declare module 'eslint-config/dist/react-rules' {
  declare module.exports: any
}

declare module 'eslint-config/gulpfile.babel' {
  declare module.exports: any
}

declare module 'eslint-config/lib/base-rules' {
  declare module.exports: any
}

declare module 'eslint-config/lib/generate-eslintrc' {
  declare module.exports: any
}

declare module 'eslint-config/lib/index' {
  declare module.exports: any
}

declare module 'eslint-config/lib/logger' {
  declare module.exports: any
}

declare module 'eslint-config/lib/react-rules' {
  declare module.exports: any
}

// Filename aliases
declare module 'eslint-config/dist/base-rules.js' {
  declare module.exports: $Exports<'eslint-config/dist/base-rules'>
}
declare module 'eslint-config/dist/generate-eslintrc.js' {
  declare module.exports: $Exports<'eslint-config/dist/generate-eslintrc'>
}
declare module 'eslint-config/dist/index.js' {
  declare module.exports: $Exports<'eslint-config/dist/index'>
}
declare module 'eslint-config/dist/logger.js' {
  declare module.exports: $Exports<'eslint-config/dist/logger'>
}
declare module 'eslint-config/dist/react-rules.js' {
  declare module.exports: $Exports<'eslint-config/dist/react-rules'>
}
declare module 'eslint-config/gulpfile.babel.js' {
  declare module.exports: $Exports<'eslint-config/gulpfile.babel'>
}
declare module 'eslint-config/lib/base-rules.js' {
  declare module.exports: $Exports<'eslint-config/lib/base-rules'>
}
declare module 'eslint-config/lib/generate-eslintrc.js' {
  declare module.exports: $Exports<'eslint-config/lib/generate-eslintrc'>
}
declare module 'eslint-config/lib/index.js' {
  declare module.exports: $Exports<'eslint-config/lib/index'>
}
declare module 'eslint-config/lib/logger.js' {
  declare module.exports: $Exports<'eslint-config/lib/logger'>
}
declare module 'eslint-config/lib/react-rules.js' {
  declare module.exports: $Exports<'eslint-config/lib/react-rules'>
}
