# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore")

    version = get_version_number
    build = increment_build_number(xcodeproj: "Crustacean.xcodeproj")
    semantic_version = "#{version}-build.#{build}"

    build_app(scheme: "Crustacean")
    upload_to_testflight
    add_git_tag(tag: semantic_version)
    push_git_tags
  end
end
